### ISSUE TITLE
[g5k] Support for subnets

### ISSUE THREAD

**Issue by msimonin** [BeyondTheClouds/enoslib#34]
Currently g5k subnets aren't supported meaning :  
- There is no way to reserve one
- There is no way to get the subnet info

At a first sight we could use a special type of g5k network to specify a subnet to reserve : 

```
networks:
  - type: subnet
     slash: 22
     roles: [] # doesn't make really sense here
```
