### ISSUE TITLE
Refresh facts when using utils playbook

### ISSUE THREAD

**Issue by msimonin** [BeyondTheClouds/enoslib#78]
Add: 

```
- name: Gather facts
  hosts: all
  tasks:
    - setup:
```

Use case: Calling `tc_apply` use the previous facts which can be out-dated. For instance when depoying openstack with enos the `up, os` phase adds some virtual ips which aren't taken into account if we don't refresh the facts here.
cc @jrbalderrama
